include:
  - project: dwp/engineering/gitlab-ci-toolbox
    ref: 3.x.x
    file: blueprints/node.yml
  - project: dwp/engineering/gitlab-ci-toolbox
    ref: 3.x.x
    file: blueprints/auto-tag-merge.yml

variables:
  NODE_IMAGE: node:16.13.2-alpine3.15@sha256:2f50f4a428f8b5280817c9d4d896dbee03f072e93f4e0c70b90cc84bd1fcfe0d
  NODE_PUBLISH_TO_GITLAB: "true"

node-coverage:
  variables:
    TEST_EXECUTABLE: "./node_modules/.bin/mocha \"tests/unit/**/*.spec.js\""
